### PR TITLE
Arrays and objects

### PR DESCRIPTION
**Pull request by reverbePrintemps**
# Context

This PR aims to tackle [the objects and arrays challenge](https://github.com/spiced-academy/honey-web-dev/blob/js-objects-and-arrays/sessions/js-objects-and-arrays/challenges-js-objects-and-arrays.md#objects-and-arrays).

# Changes

- [x] Tackled all inline exercises

# How to test

1. Clone repo
2. `npm i`
3. `npm run test`

# TODO

- [ ] Get PR reviewed

# GIF

### CODE REVIEW

**Comment by spacedoe** [comment]
Looks good, ready to merge!

**Comment by spacedoe** [comment]
However, the name of this challenge should be 'Objects', as 'Arrays and objects' is a different challenge.

**Comment by reverbePrintemps** [comment]
@spacedoe good catch! I must have messed up the rebase. I've now rebased correctly and this PR should only contain my changes for the Objects and arrays challenge : )

**Comment by spacedoe** [comment]
checked, just a couple of comments, otherwise all good and ready to merge.

**Comment by reverbePrintemps** [comment]
@spacedoe I'm not seeing any new comments. 🤔

**Comment by spacedoe** [comment]
hmm... strange, you don't see this?

image

**Comment by reverbePrintemps** [comment]
@spacedoe No I don't see those comments for some reason 🤔 But to answer to them, yes, we can define them as you mentioned. However, doing it like you suggest assumes that: 1. Homer will always be the first object in the `people` array and 2. Lisa will always be the 4th object in the people array. I suppose for the purposes of this exercise that's fine but in a scenario where that would not necessarily be true, using the Array method `find` helps tackle that problem. : )

**Comment by spacedoe** [comment]
I see, that makes sense. Thanks for the explanation!

**Pull request merged**
